# -*- coding: utf-8 -*-
"""Data_201_Final_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9mKLs6XZ9iTDhhIxP-A5-ET31JU6SZ9
"""

#Link to dataset:
#https://collegescorecard.ed.gov/data/
#I'm wrangling/cleaning the 'Most Recent Cohorts Institution' csv - Ellie

#Link to variable dictionary:
#https://collegescorecard.ed.gov/assets/InstitutionDataDocumentation.pdf

#Libraries
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.ensemble import RandomForestRegressor

#Load into dataframe
df = pd.read_csv("Most-Recent-Cohorts-Institution.csv")

df.head()

#If y'all need to search for a word in a column name
word = 'C100'
matching_cols = [col for col in df.columns if word.lower() in col.lower()]

print(matching_cols)

df.dtypes.to_dict()

df.shape

"""# Create refined df"""

selected_columns = ['INSTNM', 'CITY', 'STABBR', 'ZIP', 'LATITUDE', 'LONGITUDE', 'CONTROL', 'UGDS',
                    'C150_4', 'GRAD_DEBT_MDN', 'COSTT4_A', 'TUITIONFEE_IN', 'TUITIONFEE_OUT',
                    'PCTPELL', 'MD_EARN_WNE_P10']

df_refined = df[selected_columns].copy()

df_refined.head()

"""# Data Cleaning"""

missing_data = df_refined.isnull()
missing_counts = missing_data.sum()
missing_percentages = (missing_counts / len(df_refined)) * 100

missing_summary = pd.DataFrame({
    'Column': missing_counts.index,
    'Missing_Count': missing_counts.values,
    'Missing_Percentage': missing_percentages.values
})

missing_summary = missing_summary.sort_values('Missing_Percentage', ascending=False)

print("Columns with missing data:")
print(missing_summary[missing_summary['Missing_Count'] > 0])

"""Since COSTT4_A, TUITIONFEE_IN/_OUT have high missing values but could be integral to our analysis, I created a new column of imputated values that are like the row's."""

df_refined['COSTT4_A_IMP'] = df_refined.groupby('CONTROL')['COSTT4_A'].transform(lambda x: x.fillna(x.median()))
df_refined['TUITIONFEE_IN_IMP'] = df_refined.groupby('CONTROL')['TUITIONFEE_IN'].transform(lambda x: x.fillna(x.median()))
df_refined['TUITIONFEE_OUT_IMP'] = df_refined.groupby('CONTROL')['TUITIONFEE_OUT'].transform(lambda x: x.fillna(x.median()))

"""Since these 3 had lower NaN sums, I just did a median imputation to avoid any skewness."""

for col in ['MD_EARN_WNE_P10', 'PCTPELL', 'UGDS']:
    df_refined[col] = df_refined[col].fillna(df_refined[col].median())

"""Since LATITUDE, LONGITUDE, and GRAD_DEBT_MDN, I did not see a reason to do any imputation."""

df_refined.isna().sum()

"""**Return On Investments columns:**
ROI: time to recover tuition cost for 4 years of college if you set aside 100% of your paycheck
- <1: less than one year until you make back cost
- 2: 2 years until you make back the cost
"""

#Create return on investments columns
df_refined['ROI'] = df_refined['COSTT4_A_IMP'] * 4 / df_refined['MD_EARN_WNE_P10']

"""Reorganizing columns"""

columns = ['INSTNM', 'CITY', 'STABBR', 'CONTROL',
           'UGDS', 'C150_4', 'COSTT4_A', 'COSTT4_A_IMP',
           'TUITIONFEE_IN', 'TUITIONFEE_IN_IMP', 'TUITIONFEE_OUT', 'TUITIONFEE_OUT_IMP',
           'PCTPELL', 'GRAD_DEBT_MDN', 'MD_EARN_WNE_P10', 'ROI',
           'ZIP', 'LATITUDE', 'LONGITUDE']

df_refined = df_refined[columns]

df_refined.head()

"""# Create df and .csv's for public and private colleges"""

public_df = df_refined[df_refined['CONTROL'] == 1].copy()

private_df = df_refined[df_refined['CONTROL'].isin([2, 3])].copy()

"""If you want to separate private and private nonprofit colleges into separate dfs:"""

private_np_df = df_refined[df_refined['CONTROL'] == 2].copy()

private_fp_df = df_refined[df_refined['CONTROL'] == 3].copy()

"""# Data Analyisis 1: Multiple Regression

For the regression model, we are going to predict the graduation rate and use debt, total cost of attendance, size, and student income as predictors. most of the other ones dont really work as important predictors, for example latitide and longditiude.

First creating a correlation matrix of the predictors we are using
"""

predictors = [
    'GRAD_DEBT_MDN',   # Median student debt
    'COSTT4_A_IMP',    # Total cost of attendance
    'UGDS',            # Enrollment size
    'PCTPELL'          # % low-income students
]

df_refined['GRAD_DEBT_MDN'] = pd.to_numeric(df_refined['GRAD_DEBT_MDN'], errors='coerce')


# Create correlation matrix
correlation_matrix = df_refined[predictors].corr()

# Visualize the correlation matrix
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', center=0,
            square=True, linewidths=1, cbar_kws={"shrink": 0.8})

plt.title('Correlation Matrix of Predictor Variables')
plt.tight_layout()
plt.show()

# Print matrix
print("Correlation Matrix:")
print(correlation_matrix)

"""There are not any predictors with unusually high correlation (>0.7) leading to multicollinearity so these are the vaues we are going to use

Creating the multiple regression model
"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#Response variable = Graduation rate
response = 'C150_4'

# Prepare the data (remove missing values)
model_data = df_refined[predictors + [response]].dropna()

print(f"Using {len(model_data)} complete observations")
print(f"This represents {len(model_data)/len(df_refined)*100:.1f}% of the original data")

# Set up X and y
X_multiple = model_data[predictors]
y_multiple = model_data[response]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X_multiple, y_multiple, test_size=0.2, random_state=42
)

# Create and fit the model
multiple_model = LinearRegression()
multiple_model.fit(X_train, y_train)

# Display the coefficients
print(f"\nIntercept (β₀): {multiple_model.intercept_:.4f}")

print("\nCoefficients:")
for i, predictor in enumerate(predictors):
    print(f"  {predictor}: β_{i+1} = {multiple_model.coef_[i]:.6f}")

"""The small coefficients for cost and debt may also be influenced by differences in scale, since these variables are measured in large units (dollars), making their coefficients appear small even if they have meaningful effects.

RSME, R^2 and predicted vs actual
"""

from sklearn.metrics import r2_score

# Make predictions on test set
y_pred_multiple = multiple_model.predict(X_test)

# Calculate R²
r2_multiple = r2_score(y_test, y_pred_multiple)
print(f"R² Score: {r2_multiple:.4f}")

# RMSE STEP-BY-STEP

# Step 1: Create dataframe with actual vs predicted
results_df = pd.DataFrame({
    'actual': y_test.values,
    'predicted': y_pred_multiple
})

# Step 2: Calculate residuals (difference)
results_df['difference'] = results_df['actual'] - results_df['predicted']

# Step 3: Square the differences
results_df['squared_difference'] = results_df['difference'] ** 2

# Step 4: Mean Squared Error (MSE)
mse = results_df['squared_difference'].mean()

# Step 5: Root Mean Squared Error (RMSE)
rmse_multiple = np.sqrt(mse)

print(f"RMSE: {rmse_multiple:.4f}")

# Show predictions
print("\nSample predictions:")
print(results_df.head(10))

"""The model achieved an R^2 value of 0.4024, meaning it explains about 40% of the variation in graduation rates, which indicates a moderate fit. The RMSE of 0.1615 shows that predictions are off by about 0.16 (16 percentage points) on average, reflecting moderate prediction error. Overall, the model captures meaningful relationships but still misses some factors influencing graduation outcomes, since R^2 measures explained variation and RMSE measures average prediction error

Model vs Actual
"""

# Create a scatter plot of actual vs predicted values
plt.figure(figsize=(10, 6))

plt.scatter(y_test, y_pred_multiple, alpha=0.5)

# Perfect prediction line (y = x)
plt.plot(
    [y_test.min(), y_test.max()],
    [y_test.min(), y_test.max()],
    'r--',
    lw=2,
    label='Perfect Predictions'
)

plt.xlabel('Actual Graduation Rate')
plt.ylabel('Predicted Graduation Rate')
plt.title('Actual vs Predicted Graduation Rates')

plt.legend()
plt.tight_layout()
plt.show()

"""Residual plot"""

# Create residuals
residuals = y_test - y_pred_multiple

# Create residual plot
plt.figure(figsize=(10, 6))

plt.scatter(y_pred_multiple, residuals, alpha=0.5)

# Horizontal line at 0
plt.axhline(y=0, color='r', linestyle='--')

plt.xlabel('Predicted Graduation Rate')
plt.ylabel('Residuals')
plt.title('Residual Plot (Graduation Rate Model)')

plt.tight_layout()
plt.show()

# Summary statistics of residuals
print("Residual Statistics:")
print(f"Mean: {residuals.mean():.4f}")
print(f"Standard Deviation: {residuals.std():.4f}")

"""# Data Analysis 2: Clustering

First we need to standardize the variables
"""

from sklearn.preprocessing import StandardScaler
import pandas as pd

# Your features
features_to_use = [
    'GRAD_DEBT_MDN',
    'COSTT4_A_IMP',
    'UGDS',
    'PCTPELL'
]


# Extract selected features and drop missing values
X = df_refined[features_to_use].dropna()

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Convert back to dataframe for readability
scaled_df = pd.DataFrame(X_scaled, columns=features_to_use)

print("Sample of standardized features:")
print(scaled_df.head(10))

# Compare original vs scaled data statistics
print("Original Data Statistics:")
print(df_refined[features_to_use].describe())
print("\nScaled Data Statistics:")
print(scaled_df.describe())

"""now using the elbow method to find optimal amount of clusters"""

from sklearn.cluster import KMeans

# Calculate WCSS (Within-Cluster Sum of Squares)
wcss = []
k_range = range(2, 11)

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

# Plot the elbow curve
plt.figure(figsize=(10, 6))

plt.plot(k_range, wcss, marker='o', linewidth=2, markersize=8)

plt.xlabel('Number of Clusters (k)')
plt.ylabel('Within-Cluster Sum of Squares (WCSS)')
plt.title('Elbow Method for Optimal Number of Clusters')

plt.grid(True, alpha=0.3)
plt.xticks(k_range)

plt.tight_layout()
plt.show()

"""we will use 5 clusters for our analysis

now we will also use the silhouette method to see what the best defined clusters are
"""

from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

# Calculate silhouette scores for different numbers of clusters
silhouette_scores = []

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    cluster_labels = kmeans.fit_predict(X_scaled)

    silhouette_avg = silhouette_score(X_scaled, cluster_labels)
    silhouette_scores.append(silhouette_avg)

    print(f"For k = {k}, silhouette score = {silhouette_avg:.4f}")

# Plot silhouette scores
plt.figure(figsize=(10, 6))

plt.plot(k_range, silhouette_scores, marker='s', linewidth=2, markersize=8, color='green')

plt.xlabel('Number of Clusters (k)')
plt.ylabel('Silhouette Score')
plt.title('Silhouette Scores for Different k Values')

plt.grid(True, alpha=0.3)
plt.xticks(k_range)

plt.tight_layout()
plt.show()

"""The 2 methods pretty well agree so we will do 5 clusters in our analysis

K-Means analysis
"""

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Set the number of clusters based on your analysis
n_clusters = 5

# Train the K-means model
kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
cluster_labels = kmeans.fit_predict(X_scaled)


cluster_data = X.copy()  # use the cleaned data you clustered on
cluster_data['cluster'] = cluster_labels

# Display cluster distribution
print("\nCluster distribution:")
print(cluster_data['cluster'].value_counts().sort_index())

# Calculate silhouette score for final model
final_silhouette = silhouette_score(X_scaled, cluster_labels)
print(f"\nFinal Silhouette Score: {final_silhouette:.4f}")

"""Cluster visualization with PCA"""

from sklearn.decomposition import PCA

# Apply PCA to reduce to 2 dimensions for visualization
pca = PCA(n_components=2, random_state=42)
X_pca = pca.fit_transform(X_scaled)

# Create a dataframe with PCA results
pca_df = pd.DataFrame({
    'PC1': X_pca[:, 0],
    'PC2': X_pca[:, 1],
    'cluster': cluster_labels
})

# Plot the clusters
plt.figure(figsize=(12, 8))

for cluster in range(n_clusters):
    cluster_subset = pca_df[pca_df['cluster'] == cluster]  # renamed to avoid overwriting
    plt.scatter(
        cluster_subset['PC1'],
        cluster_subset['PC2'],
        label=f'Cluster {cluster}',
        alpha=0.6,
        s=50
    )

# Plot cluster centers (converted into PCA space)
centers_pca = pca.transform(kmeans.cluster_centers_)
plt.scatter(
    centers_pca[:, 0],
    centers_pca[:, 1],
    c='red',
    marker='X',
    s=300,
    edgecolors='black',
    linewidths=2,
    label='Centroids'
)

# Labels and formatting
plt.xlabel(f'PC1 ({pca.explained_variance_ratio_[0]:.1%} variance)')
plt.ylabel(f'PC2 ({pca.explained_variance_ratio_[1]:.1%} variance)')
plt.title('K-Means Clusters of Colleges (PCA Visualization)')

plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Print explained variance
print(f"\nTotal variance explained by first 2 components: {sum(pca.explained_variance_ratio_):.1%}")

"""analyzing the cluster means"""

# Calculate mean feature values for each cluster
cluster_means = cluster_data.groupby('cluster')[features_to_use].mean()

print("Mean feature values for each cluster:")
print(cluster_means.round(3))

"""The clusters show clear differences in cost, debt, and student demographics across institutions. For example, Cluster 4 represents high-cost, high-debt schools with lower Pell Grant percentages, while Cluster 1 consists of lower-cost schools serving a higher proportion of low-income students. Overall, the clustering reveals distinct types of colleges, ranging from more elite, expensive institutions to more accessible, lower-cost schools with different student populations.

Radar plots for the clusters
"""

# Number of features
num_features = len(features_to_use)

# Angles for radar chart
angles = np.linspace(0, 2*np.pi, num_features, endpoint=False).tolist()
angles += angles[:1]  # complete circle

# Create subplots
fig, axes = plt.subplots(1, n_clusters, figsize=(n_clusters*5, 5),
                         subplot_kw=dict(polar=True))

# Fix for single cluster case
if n_clusters == 1:
    axes = [axes]

# Normalize cluster means (VERY IMPORTANT for radar chart)
cluster_means_normalized = (cluster_means - cluster_means.min()) / (cluster_means.max() - cluster_means.min())

# Plot each cluster
for i, ax in enumerate(axes):
    values = cluster_means_normalized.iloc[i].values.tolist()
    values += values[:1]  # complete circle

    ax.plot(angles, values, linewidth=2)
    ax.fill(angles, values, alpha=0.25)

    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(features_to_use, fontsize=10)

    ax.set_ylim(0, 1)
    ax.set_title(f'Cluster {i} Profile', fontsize=14, pad=20)

    ax.grid(True)

plt.tight_layout()
plt.show()

"""# Data Visualizations"""

import matplotlib.pyplot as plt
import seaborn as sns

# The `X` DataFrame contains the features used for clustering and retains the original index from `df_refined`.
# Add the cluster labels to this DataFrame.
X_with_clusters = X.copy()
X_with_clusters['cluster'] = cluster_labels

# Now, merge `C150_4` from `df_refined` back into this DataFrame using the index.
# We need to ensure C150_4 values are aligned with the correct clustered data.
plot_data_clustered = X_with_clusters.merge(
    df_refined[['C150_4']],
    left_index=True,
    right_index=True,
    how='left'
)

# Drop any rows where 'C150_4' is NaN, as these cannot be plotted.
plot_data_clustered = plot_data_clustered.dropna(subset=['C150_4'])

# Create a FacetGrid for scatter plots by cluster
g = sns.relplot(
    data=plot_data_clustered,
    x='COSTT4_A_IMP',
    y='C150_4',
    col='cluster',
    col_wrap=3,
    height=4,
    aspect=1.2,
    kind='scatter',
    alpha=0.6
)

g.set_axis_labels('Imputed Cost of Attendance (COSTT4_A_IMP)', 'Graduation Rate (C150_4)')
g.set_titles('Cluster {col_name}')
g.fig.suptitle('Cost of Attendance vs. Graduation Rate by Cluster', y=1.02) # Adjust title position

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

# The `X` DataFrame contains the features used for clustering and retains the original index from `df_refined`.
# Add the cluster labels to this DataFrame.
X_with_clusters = X.copy()
X_with_clusters['cluster'] = cluster_labels

# Now, merge `C150_4` from `df_refined` back into this DataFrame using the index.
# We need to ensure C150_4 values are aligned with the correct clustered data.
plot_data_clustered = X_with_clusters.merge(
    df_refined[['C150_4']],
    left_index=True,
    right_index=True,
    how='left'
)

# Drop any rows where 'C150_4' is NaN, as these cannot be plotted.
plot_data_clustered = plot_data_clustered.dropna(subset=['C150_4'])

# Create a FacetGrid for scatter plots by cluster
g = sns.relplot(
    data=plot_data_clustered,
    x='PCTPELL',
    y='C150_4',
    col='cluster',
    col_wrap=3,
    height=4,
    aspect=1.2,
    kind='scatter',
    alpha=0.6
)

g.set_axis_labels('Percentage of Pell Grant Recipients (PCTPELL)', 'Graduation Rate (C150_4)')
g.set_titles('Cluster {col_name}')
g.fig.suptitle('Pell Grant Recipients vs. Graduation Rate by Cluster', y=1.02) # Adjust title position

plt.tight_layout()
plt.show()

"""make the csv file"""

df_refined.to_csv("cleanData.csv", index=False)